name: BouncyBeds
main: me.cmesh.BouncyBeds.BouncyBeds
version: 1.6
softdepend: [AntiCheat]
commands:
   bounce:
      description: set bounce on beds
      usage: |
          /bounce true
          /bounce false